tags:
  - stores
summary: Post New Store
description: Post create new store.
requestBody:
  content:
    application/json:
      schema:
        $ref: '../../models/store.yaml'
responses:
  "200":
    description: Store is created
    content:
      application/json:
        schema:
          $ref: '../../models/store.yaml'
  "401":
    $ref: '../../models/errors/401-unauthorized.yaml'
  "500":
    $ref: '../../models/errors/500-fatal.yaml'
