tags:
  - stores
summary: Put Store
description: Update store by ID
parameters:
  - name: id
    in: path
    description: ID of store
    required: true
    schema:
      type: integer
requestBody:
  content:
    application/json:
      schema:
        $ref: '../../models/store.yaml'
responses:
  "200":
    description: Account is updated
    content:
      application/json:
        schema:
          $ref: '../../models/store.yaml'
  "400":
    $ref: '../../models/errors/400-badRequest.yaml'
  "401":
    $ref: '../../models/errors/401-unauthorized.yaml'
  "500":
    $ref: '../../models/errors/500-fatal.yaml'
