tags:
  - accounts
summary: Get list of Account
description: Get list of Account
parameters:
 - name: limit
   in: query
   description: Limit max number of elements in the list
   schema:
     type: integer
 - name: offset
   in: query
   description: Starting offset
   schema:
     type: integer
responses:
  "200":
    description: Account is created
    content:
      application/json:
        schema:
          $ref: '../../models/account.yaml'
  "401":
    $ref: '../../models/errors/401-unauthorized.yaml'
  "500":
    $ref: '../../models/errors/500-fatal.yaml'
